server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mauriciosodre/spring-services-configurations.git
          search-paths: 'greeting-service*'